config/routes.rb
Rails.application.routes.draw do

 root "catalogs#index"

 ##STATIC PAGES ROUTES STARTS HERE####
 get "/terms-and-conditions" => "statics#terms_conditions"

 get "/privacy-policy" => "statics#privacy_policy"

 get "/content_not_available" => "statics#content_not_available"

 get "/faq" => "statics#faq"

 get "/contact-us" => "statics#contact_us"

 ##STATIC PAGES ROUTES ENDS HERE####

 ##USERS PAGES ROUTES STARTS HERE####
 
	namespace :users do
	  get 'register'
	  get 'login'
	  post 'sign_in'
	  post 'sign_up'
	  get 'welcome'
    get 'manage_profiles'
    get 'account_details'
    get 'forgot_password'
    get 'watch_list'
    get 'change_password'
    get 'change_profile'
	  post 'sign_out'
	  get  'verify_otp'
    post 'update_profile'
    post 'delete_profile'
    get 'settings'
    get 'registered_devices'
    get 'streaming'
    get 'parent_control'
    get 'create_pin'
    match 'activate_code',via: [:get,:post]
    match  'update_personal_details',via: [:get,:post]
    match  'add_profile',via: [:get,:post]
	  post 'validate_otp'
	  post 'resend_otp'
	  post 'subscriptions'
	end
  get "/users/edit_profile/:profile_id" => "users#edit_profile"
  get "/users/remote_profile/:profile_id" => "users#remote_profile"

 ##USERS PAGES ROUTES STARTS HERE####

 ##PLANS PAGES ROUTES STARTS HERE####
  get '/plans' => 'plans#all_plans'
  get '/plans/m_plans' => 'plans#mobile_all_plans'
 
  get '/plans/plans_summary' => 'plans#plans_summary'
  get '/plans/m_plans_summary' => 'plans#mobile_plans_summary'
 
  get '/plans/plans_purchase' => 'plans#plans_purchase'
  get '/plans/m_plans_purchase' => 'plans#mobile_plans_purchase'
 
  post '/plans/payment_url' => 'plans#payment_url'
  post '/plans/m_payment_url' => 'plans#mobile_payment_url'

  get '/plans/purchase_plans' => 'plans#purchase_plans'
  get '/plans/m_purchase_plans' => 'plans#mobile_purchase_plans'
 
  get '/payment/payment_processing' => 'plans#payment_processing'
  get '/payment/m_payment_processing' => 'plans#mobile_payment_processing'
 
  get '/payment/payment_success' => 'plans#payment_success'
  get '/payment/m_payment_success' => 'plans#mobile_payment_success'
 
  get '/payment/payment_failed' => 'plans#payment_failed'
  get '/payment/m_payment_failed' => 'plans#mobile_payment_failed'
 
  post '/payment/payment_canceled' => 'plans#payment_canceled'
  post '/payment/m_payment_canceled' => 'plans#mobile_payment_canceled'
 
  # post '/payment/payment_response' => 'plans#payment_response'
  # post '/payment/m_payment_response' => 'plans#mobile_payment_response'
 
  match 'payment/payment_response' => 'plans#payment_response', via: [:get, :post]
  match 'payment/m_payment_response' => 'plans##mobile_payment_response', via: [:get, :post]
 
  get '/plans/apply_promocode' => 'plans#apply_promocode'
  # get '/plans/m_apply_promocode' => 'plans##mobile_apply_promocode'

  get '/plans/view_plans' => 'plans#view_plans'
  get '/plans/m_view_plans' => 'plans##mobile_view_plans'

  get '/plans/plan_details/:id', to: 'plans#plan_details', as: 'plan'
  get '/plans/m_plan_details/:plan_id' => 'plans##mobile_plan_details'

   get '/plans/modify_plans' => 'plans#modify_plans'
  get '/plans/m_modify_plans' => 'plans##mobile_modify_plans'

 ##PLANS PAGES ROUTES ENDS HERE####


 ###SEARCH ROUTES STARTS HERE#################
 match "/search" => "search#index",via: [:get,:post]
 # get "/search" => "search#index"

 ###SEARCH ROUTES ENDS HERE#################


 ##CATALOGS PAGES ROUTES STARTS HERE####
 get "/all_channels" => "catalogs#all_channels"
 get "/:catalog_name" => "catalogs#show_catalog_item"
 get "/:catalog_name/all" => "catalogs#all_items_list"
 get "/:catalog_name/:show_name" => "catalogs#item_details"
 get "/:catalog_name/others/all" => "catalogs#other_tvshows"
 get "/:catalog_name/:show_name/all_episodes" => "catalogs#all_episodes"
 get "/:catalog_name/:genre/all" => "catalogs#genre_all_items"
 get "/:catalog_name/:show_name/:item_name" => "catalogs#episode_details"
 ##CATALOGS PAGES ROUTES ENDS HERE####

end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def index
  	begin
  	response = Rails.cache.fetch("home_page_list", expires_in: CACHE_EXPIRY_TIME) {
      Ott.get_home_list      
     }
  	 @home_list = response["data"]["catalog_list_items"]
  	 @items = @home_list.drop(1)
  	rescue Exception => e
      logger.info e.message
  	 Rails.cache.delete("home_page_list")
  	 @home_list = []
    end 
  end

  def show_catalog_item
   begin
    response = Rails.cache.fetch("catalog_item_list_#{params[:catalog_name]}", expires_in: CACHE_EXPIRY_TIME){
     Ott.get_items_list(params[:catalog_name])
    }
    @items_list = response["data"]["catalog_list_items"]
    @catalog_items = @items_list.drop(1)
    @meta_title = response["data"]["display_title"]
    @meta_keywords = ""
    @layout_scheme = response["data"]["layout_scheme"]
    # subscribe_item = response["data"]["catalog_list_items"].collect{|x| x if(x["layout_type"] == "t_subscription")}.compact.first
    # @subscribe_img = subscribe_item["list_item_object"]["banner_image"]
    # @plan_det = subscribe_item["catalog_list_items"][0]["plans"].first
   rescue Exception => e
    redirect_to "#{SITE}/500"
      logger.info e.message
     Rails.cache.delete("catalog_item_list_#{params[:catalog_name]}")
     @items_list = []
    end
  end

  def all_items_list
    begin
    # next_page = "true"
    # page_size = 20
    # if params[:page_no].present?
    #   page_number = params[:page_no].to_i
    # else
    #   page_number = 0
    # end
      # response = Rails.cache.fetch("all_items_list_#{params[:catalog_name]}_#{page_number}", expires_in: CACHE_EXPIRY_TIME){
      #  Ott.get_items_list_with_pagination(params[:catalog_name],page_number,page_size)
      # }
      response = Rails.cache.fetch("all_items_list_#{params[:catalog_name]}", expires_in: CACHE_EXPIRY_TIME){
       Ott.get_items_list(params[:catalog_name])
      }
      @all_items = response["data"]["catalog_list_items"]
      @layout_type =  response["data"]["layout_type"]
      @layout_scheme = response["data"]["layout_scheme"]
      @title = response["data"]["display_title"]
      @next_page = true
    rescue Exception => e
      logger.info e.message
     Rails.cache.delete("all_items_list_#{params[:catalog_name]}")
     @all_items = []
    end
  end

  def item_details
     begin
       item_response = Rails.cache.fetch("item_details_#{params[:catalog_name]}_#{params[:show_name]}", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_items_details(params[:catalog_name],params[:show_name])
        }
      if item_response["data"].has_key?("episode_flag")
        @layout_scheme = item_response["data"]["catalog_object"]["layout_scheme"]
        @episode_details = item_response["data"]
        p @episode_details['item_caption'].inspect
        @image_url = @episode_details["thumbnails"]['large_16_9']['url']
        tvshow_response =  Rails.cache.fetch("all_epsiodes_#{params[:catalog_name]}_#{params[:show_name]}", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_all_epsiodes(params[:catalog_name],params[:show_name])
        }
        @all_episodes = tvshow_response["data"]["items"]
        catalog_response = Rails.cache.fetch("more_details_#{params[:catalog_name]}", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_catalog_details(params[:catalog_name])
        }
        if @all_episodes.count > 0
          @new_play_url,@key =  get_play_url_key(@all_episodes.first)
        else
          @new_play_url,@key = ""
        end
        @other_items = catalog_response["data"]["items"]
        @catalog_name = catalog_response["data"]["name"]
        @tvshow_name = item_response["data"]["title"]
        render "episode_details"
      else
        @item_details = item_response["data"]
        @theme = item_response["data"]["theme"]
        if @theme == "linear"
          programs_response = Ott.get_channel_programs(params[:catalog_name],params[:show_name])
          @channel_all_programs = programs_response["data"]["items"]
          channels_response = Ott.get_all_channels
          @all_channels = channels_response["data"]["items"]
        end
        @new_play_url,@key =  get_play_url_key(item_response['data'])
        more_item_response = Rails.cache.fetch("more_items_#{params[:catalog_name]}_#{@item_details['genres'][0]}", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_items_genre(params[:catalog_name],@item_details['genres'][0])
       }
       @layout_scheme = item_response["data"]["catalog_object"]["layout_scheme"]
       @genere_items = more_item_response["data"]["items"]
       @layout_type = item_response["data"]["catalog_object"]["layout_type"]
      end
    rescue Exception => e
      redirect_to "#{SITE}/500"
      logger.info e.message
      Rails.cache.delete("item_details_#{params[:catalog_name]}_#{params[:show_name]}")
      @item_details = []
    end
  end

  def episode_details
     begin
      response = Rails.cache.fetch("item_details_#{params[:catalog_name]}_#{params[:show_name]}_#{params[:item_name]}", expires_in: CACHE_EXPIRY_TIME){
       Ott.get_episode_details(params[:catalog_name],params[:show_name],params[:item_name])
      }
      @episode_details = response["data"]
      @layout_scheme = response["data"]["catalog_object"]["layout_scheme"]
      @new_play_url,@key =  get_play_url_key(response["data"])
      tvshow_response =  Rails.cache.fetch("all_epsiodes_#{params[:catalog_name]}_#{params[:show_name]}", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_all_epsiodes(params[:catalog_name],params[:show_name])
        }
      @all_episodes = tvshow_response["data"]["items"]
      catalog_response = Rails.cache.fetch("more_details_#{params[:catalog_name]}", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_catalog_details(params[:catalog_name])
        }
      @other_items = catalog_response["data"]["items"]
      @catalog_name = catalog_response["data"]["name"]
      @tvshow_name = response["data"]["show_name"]
      @layout_type = catalog_response["data"]["catalog_object"]["layout_type"]
    rescue Exception => e
      redirect_to "#{SITE}/500"
      logger.info e.message
     Rails.cache.delete("item_details_#{params[:catalog_name]}_#{params[:show_name]}_#{params[:item_name]}")
     @epsiode_details = []
    end

  end

  def genre_all_items
   begin
      items_response = Rails.cache.fetch("all_items_#{params[:catalog_name]}_#{params[:genre]}", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_items_genre(params[:catalog_name],params[:genre])
       }
    @all_genere_items = items_response["data"]["items"]
    @theme = items_response["data"]["theme"]
    @layout_scheme =  items_response["data"]["catalog_object"]["layout_scheme"]
   rescue Exception => e
    logger.info e.message
    @all_genere_items = []
     Rails.cache.delete("all_items_#{params[:catalog_name]}_#{params[:genre]}")
   end
  end

  def other_tvshows
   begin 
    items_response = Rails.cache.fetch("other_tvshows_#{params[:catalog_name]}", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_catalog_details_with_pagination(params[:catalog_name])
       }
    @title = "Other  "+items_response["data"]["name"]
    @all_tvshows = items_response["data"]["items"]
    @layout_scheme =  items_response["data"]["catalog_object"]["layout_scheme"]
    rescue
      Rails.cache.delete("other_tvshows_#{params[:catalog_name]}")
      @all_tvshows = []
    end
  end
  
  def all_episodes
    next_page = "true"
    if params[:page_no].present?
     page_number = params[:page_no].to_i
    else
     page_number = 0
    end
    response = Ott.get_all_epsiodes_with_pagination(params[:catalog_name],params[:show_name],page_number)
    no_of_pages = response["data"]["total_items_count"]/10.round
    items =  response["data"]["items"].collect{|x|x["title"]+"$"+x["thumbnails"]["small_16_9"]["url"]+"$"+get_duration_time(x['duration_string']) +"$"+"/"+params[:catalog_name]+"/"+params[:show_name]+"/"+x["friendly_id"]+"$"+x['episode_number']}
    if page_number+1 > no_of_pages
     next_page = "false"
    end
    render :json => {:status => true,:episodes => items,:next_page => next_page,:pageno => page_number+1}
  end

  def all_channels
   begin 
    channels_response = Rails.cache.fetch("all_channels", expires_in: CACHE_EXPIRY_TIME){
         Ott.get_all_channels
       }
     @all_channels = channels_response["data"]["catalog_list_items"]
    rescue
      Rails.cache.delete("all_channels")
      @all_channels = []
    end
  end





private

  def encrypt_play_url(url)
    new_url = ""
    aes = OpenSSL::Cipher::Cipher.new('AES-128-CBC')
    aes.encrypt
    key = aes.random_key
    aes.key = key
    e_key = Base64.encode64(key).gsub(/\n/, '')
    encrypted = aes.update(url) + aes.final
    new_url = Base64.encode64(encrypted).gsub(/\n/, '')
    return new_url,e_key
  end

  def get_play_url_key(response)
    url = sign_smarturl response['play_url']['saranyu']['url']
    if response["theme"] == "live"
       play_url = url["adaptive_urls"][0]['playback_url']
    else
      play_url = url["adaptive_urls"].collect{|x|x["playback_url"] if x["label"] == "laptop_free_#{$region.downcase}_logo"}.compact.first
      play_url = url["adaptive_urls"].collect{|x|x["playback_url"] if x["label"] == "laptop_free_in"}.compact.first if play_url.nil?
    end
    if play_url.nil?
      new_play_url = ""
    else
      new_play_url = encrypt_play_url(play_url)
    end
    return new_play_url
  end


end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/views/catalogs/all_channels.html.erb
<%
meta title: "All tv channels",
     description: "All tv channels",
     keywords: "All tv channels"
%>
<%if @all_channels.count > 0%>
<section class="full-width-content inside-container top-bg-gradient padding-top-80 padding-top-145 light min-height-div padding-bottom-20">
  <div class="row h-100">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
      <div class="row">
       <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
      <h2 class="margin-top-25 margin-bottom-20 text-capitalize">All Channels</h2>
    </div>
    </div>
    <div class="row row-show-list all_show_horizontal_title">
     <%@all_channels.each do |i|%>
        <div class="item rounded">                                             
          <a href="<%=get_item_url(i)%>">
          <%if i['access_control']['is_free'] == false%>
            <span class="text-uppercase premium-txt">Premium</span>
          <%end%>
          <img src="<%=i["thumbnails"]["l_medium"]["url"]%>" class="rounded" alt="<%=i['title']%>" title="<%=i['title']%>">
            <span class="list-tile-title"><%=i['title']%></span>
          </a>
        </div>
      <%end%>
    </div>  
    </div>  
  </div>
<%=render "layouts/page_height_setting"%>
</section>
<%else%>
<div class="light no-items-found">
    <img src="/assets/no_content.svg" class="margin-bottom-10 welcome_page_image"  alt="" title="">
    <p class="font-medium margin-top-25 margin-bottom-0"><strong>Sorry!</strong></p>
    <p class="font-light margin-top-0 margin-bottom-5">There is no channels to show</p>
    <p class="pull-left w-100 margin-top-20 margin-bottom-15 text-center">
      <a href="/" class="text-uppercase btn btn-outline-primary gradient1 radius-button">go back</a>
    </p>
  </div>
<%end%>

app/views/catalogs/all_items_list.html.erb
<%
meta title: "#{@title}",
     description: "",
     keywords: ""
%>
<%if @all_items.count > 0%>
<section class="full-width-content inside-container top-bg-gradient padding-top-80 padding-top-145 light min-height-div padding-bottom-20">
  <div class="row h-100">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
      <div class="row">
       <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
      <h2 class="margin-top-25 margin-bottom-20 text-capitalize heading_title_color" style="<%=get_title_item_color(@layout_scheme)%>"><%=@title%></h2>
    </div>
    </div>
    
   <%if @layout_type == "t_2_3_movie" || @layout_type == "movies" 
      class_name = "row-movie-list all_movie_vertical" 
      title = "no"        
     else
      class_name = "row-show-list all_show_horizontal_title" 
      title = "yes"        
    end%>
    <div class="row <%=class_name%>">
     <%@all_items.each do |i|%>
        <div class="item <%= title == "yes" ? "rounded" : ""%>">                                                              
          <a href="<%=get_item_url(i)%>">
          <%if i['access_control']['is_free'] == false%>
            <span class="text-uppercase premium-txt">Premium</span>
          <%end%>
          <%if @layout_type == "t_1_1_album" || @layout_type == "songs"%>
          <img src="<%=i["thumbnails"]["medium_16_9"]["url"]%>" class="rounded" alt="<%=i['title']%>" title="<%=i['title']%>">
          <%else%>
          <img src="<%=get_image_url(i,@layout_type)%>" class="rounded" alt="<%=i['title']%>" title="<%=i['title']%>">
          <%end%>
          <%if title == "yes"%>
            <span class="list-tile-title"><%=i['title']%></span>
          <%end%>
          </a>
        </div>
      <%end%>
    </div>  
     <%#if @all_items.count > 10%> 
       <!--  <div class="text-center margin-bottom-25 margin-top-20" id="load_more_link">
            <a href="javascript:void(0);" class="inline-block radius-button black-button text-uppercase" id="load_more_all_items">Load more</a>
        </div> -->
      <%#end%>  
    </div>  
  </div>
<%=render "layouts/page_height_setting"%>
</section>
<%else%>
  <div class="light no-items-found">
    <img src="/assets/no_content.svg" class="margin-bottom-10 welcome_page_image"  alt="" title="">
    <p class="font-medium margin-top-25 margin-bottom-0"><strong>Sorry!</strong></p>
    <p class="font-light margin-top-0 margin-bottom-5">There is no content to show</p>
    <p class="pull-left w-100 margin-top-20 margin-bottom-15 text-center">
      <a href="/" class="text-uppercase btn btn-outline-primary gradient1 radius-button">go back</a>
    </p>
  </div>
<script type="text/javascript">
  var window_height = window.outerHeight;
    var window_height = window_height - 153;
    $('.no-items-found').css('min-height',window_height+'px');
</script>  
 <%end%>
<script type="text/javascript">
/*$(document).ready(function(){
  $("#load_more_all_items").click(function(){
    $.ajax({
    url: "/classic-all-movies/all",
    type: "GET",
    data: { },
    success: function(response,status){
    }
  });
  })
})*/

</script>

app/views/catalogs/genre_all_items.html.erb
<%
   meta title: "More In #{params[:genre]}",
    description: "#{params[:genre]}",
    keywords: "#{params[:genre]}"
%>
<section class="full-width-content inside-container top-bg-gradient min-height-div padding-top-80 padding-top-145 light">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
     <div class="row">
     <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
    <h2 class="margin-bottom-20 margin-top-25 text-capitalize heading_title_color" style="<%=get_title_item_color(@layout_scheme)%>">More in  <%=params[:genre].capitalize%></h2>
    </div>
    </div>
    <div class="row row-<%=@theme == "video" ? "show" : "movie"%>-list">
     <%@all_genere_items.each do |i|%>
        <div class="item">                                                              
          <a href="<%=get_item_url(i)%>">
          <%if i['access_control']['is_free'] == false%>
            <span class="text-uppercase premium-txt">Premium</span>
          <%end%>
          <%if @theme == "video"
            img_url = i["thumbnails"]["medium_16_9"]["url"]
          else
            img_url = i["thumbnails"]["medium_2_3"]["url"]
          end
            %>
          <img src="<%=img_url%>" class="rounded" alt="<%=i['title']%>" title="<%=i['title']%>">
          </a>
        </div>
      <%end%>
    </div>
    </div>  
  </div>
<%=render "layouts/page_height_setting"%>  
</section>

app/views/catalogs/index.html.erb
<%
meta title: "Shemaroo Entertainment Limited",
     description: "Shemaroo",
     keywords: %w(Shemaroo)
%>
<section class="banner-section padding-top-82 padding-top-145">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-">
      <div id="banner-carousel" class="owl-carousel owl-theme">
        <%@home_list[0]['catalog_list_items'].each do |h|%>
          <div class="item">
            <a href="<%=get_item_url(h)%>">            
            <img src="<%=get_image_url(h,@home_list[0]["layout_type"])%>" alt="<%=h['title']%>" title="<%=h['title']%>" class="d-none d-md-block rounded">
            <img src="<%=h["thumbnails"]["xl_image_16_9"]["url"]%>" alt="<%=h['title']%>" title="<%=h['title']%>" class="d-block d-md-none rounded">
            <!-- <img src="/assets/big_play.svg" alt="<%#=h['title']%>" title="<%#=h['title']%>"> -->
            </a>
          </div>
        <%end%>           
      </div>
    </div>
  </div>
</section>
    
<div class="min-height-div">    
  <section class="full-width-content home-page light" id="home_catalog_items" style="min-height: 1000px;">
  <%@items.each_with_index do |list,index|%>
  <%if index != 0%>
   <%if list['catalog_list_items'].count > 0%>
    <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- title_color_<%=index%>">
        <div class="row">
          <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-">
            <a href="<%=list["home_link"]%>" id="home_title_<%=index%>" style="display:none;">
              <h2 class="margin-bottom-15 text-capitalize heading_title_color" style="<%=get_title_item_color(list['layout_scheme'])%>"><%=list['display_title']%></h2></a>
              <%unless list["home_link"].blank?%>
                <a href="<%=list["home_link"]%>" class="text-uppercase pull-right see-more all_items_<%=index%>" style="display:none;">see more</a>
              <%end%>
            </div>
          </div>
          <div id="bollywood-classic-carousel_<%=index%>" class="owl-carousel vertical-image owl-theme" data-item-det="<%=@items[index]["layout_type"]%>$<%=list['catalog_list_items'].count%>$<%=get_item_color(list['layout_scheme'])%>">
            <%list['catalog_list_items'].each do |item|%>
              <div class="item <%=get_image_height(@items[index]["layout_type"])%>">
                <a href="<%=get_item_url(item)%>">
                <%if item["access_control"]["is_free"] == false%>
                  <span class="premium-txt text-uppercase">premium</span>
                <%end%>
                <img src="<%=get_image_url(item,@items[index]["layout_type"])%>" class="rounded" alt="<%=item["title"]%>" title="<%=item["title"]%>">
                </a>
              </div> 
            <%end%>             
          </div>           
        </div>
      </div>
    <%end%> 
    <%end%> 
  <%end%>
  <%=render "layouts/page_height_setting"%>
</section>
</div>

<script>
 var window_height = window.outerHeight;
  var window_height = window_height - 231;
  $('.min-height-div').css('min-height',window_height+'px');
$(document).ready(function() {
var navigation = [
      '<span aria-label="' + 'Previous' + '"><img src="/assets/big_left_arrow.svg" alt="" title=""></span>',
      '<span aria-label="' + 'Next' + '"><img src="/assets/big_right_arrow.svg" alt="" title=""></span>'
    ];
  $('#banner-carousel').owlCarousel({
    loop:true,
    autoplay: true,
    margin:10,
    nav:true,
    dots: false,
    //navText: navigation,
    navSpeed: 1000,
    responsive:{
        0:{
            items:1,
            stagePadding: 39,
        },
        576:{
            items:1,
            stagePadding: 49,
        },
        768:{
            items:1,
            stagePadding: 59,
        },
        992:{
            items:1,
            stagePadding: 69,
        },
        1200:{
            items:1,
            stagePadding: 96,
        }
    }
  });

  var items_count = "<%=@items.count-1%>"
    for (i = 1; i <= items_count; i++) {
    var auto_loop_status = false;
    var owl = $("#bollywood-classic-carousel_"+i);
    if($("#bollywood-classic-carousel_"+i).data("item-det") != undefined){
    var det = $("#bollywood-classic-carousel_"+i).data("item-det").split("$");
    var total_item_cnt =  det[1];
    var layout_type = det[0];
    var color = det[2].split("|")
    // $("body").append("<style>.title_color_"+i+" h2:before{background: linear-gradient(to right,"+color[0]+", "+color[1]+");}</style>");
    if(layout_type == "t_16_9_big" || layout_type == "t_16_9_small"){
     var no_of_items = 5;
     var items_0 = 1
       var items_576 = 2
       var items_768 = 3
       var items_992 = 4
     if(total_item_cnt > 5){
       // auto_loop_status = true
       $(".all_items_"+i).show();
       
     }
    }
    else if(layout_type == "t_1_1_plain" || layout_type == "t_1_1_album"){
     var no_of_items = 6;
     var items_0 = 2
       var items_576 = 3
       var items_768 = 4
       var items_992 = 5
     if(total_item_cnt > 6){
       // auto_loop_status = true
       $(".all_items_"+i).show();
       
     }
    }
    else{
      var no_of_items = 7
      var items_0 = 2
      var items_576 = 3
      var items_768 = 4
      var items_992 = 5
     if(total_item_cnt > 7){
      // auto_loop_status = true
      $(".all_items_"+i).show();
     }
    }

  owl.owlCarousel({
    loop: auto_loop_status,
    margin:10,
    nav:true,
    dots: false,
    stagePadding: 50,
    navText: navigation,
    responsive:{
      0:{
          items: items_0,
          stagePadding: 25
      },
      576:{
          items: items_576,
      },
      768:{
          items: items_768
      },
      992:{
          items: items_992
      },
      1200:{
          items: no_of_items
      }
    }
  });
}
 $("#home_title_"+i).show();
 }
 $("#home_catalog_items").css("min-height","1px");
});  
</script> 

app/views/catalogs/other_tvshows.html.erb
<%
meta title: "#{@title}",
     description: "",
     keywords: ""
%>
<section class="full-width-content inside-container top-bg-gradient padding-top-80 padding-top-145 light min-height-div padding-bottom-20">
  <div class="row h-100">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
    <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- listing-page">
      <h2 class="margin-top-25 margin-bottom-20 text-capitalize heading_title_color" style="<%=get_title_item_color(@layout_scheme)%>"><%=@title%></h2>
      </div>
      </div>
    <%if @all_tvshows.count > 0%>
    <div class="row row-show-list all_show_horizontal_title">
     <%@all_tvshows.each do |i|%>
        <div class="item rounded">                                      
          <a href="<%=get_item_url(i)%>">
          <%if i['access_control']['is_free'] == false%>
            <span class="text-uppercase premium-txt">Premium</span>
          <%end%>
          <img src="<%=i["thumbnails"]["medium_16_9"]["url"]%>" class="rounded" alt="<%=i['title']%>" title="<%=i['title']%>">
            <span class="list-tile-title"><%=i['title']%></span>
          </a>
        </div>
      <%end%>
    </div>
    <%else%>
    <div class="light no-items-found">
      <h2 class="margin-top-25 margin-bottom-20 text-capitalize 1-100 gradient1" style="">No items found</h2>
    </div>
    <%end%>
    </div>  
  </div>
<%=render "layouts/page_height_setting"%>

</section>