config/routes.rb
Rails.application.routes.draw do

 root "catalogs#index"

 ##STATIC PAGES ROUTES STARTS HERE####
 get "/terms-and-conditions" => "statics#terms_conditions"

 get "/privacy-policy" => "statics#privacy_policy"

 get "/content_not_available" => "statics#content_not_available"

 get "/faq" => "statics#faq"

 get "/contact-us" => "statics#contact_us"

 ##STATIC PAGES ROUTES ENDS HERE####

 ##USERS PAGES ROUTES STARTS HERE####
 
	namespace :users do
	  get 'register'
	  get 'login'
	  post 'sign_in'
	  post 'sign_up'
	  get 'welcome'
    get 'manage_profiles'
    get 'account_details'
    get 'forgot_password'
    get 'watch_list'
    get 'change_password'
    get 'change_profile'
	  post 'sign_out'
	  get  'verify_otp'
    post 'update_profile'
    post 'delete_profile'
    get 'settings'
    get 'registered_devices'
    get 'streaming'
    get 'parent_control'
    get 'create_pin'
    match 'activate_code',via: [:get,:post]
    match  'update_personal_details',via: [:get,:post]
    match  'add_profile',via: [:get,:post]
	  post 'validate_otp'
	  post 'resend_otp'
	  post 'subscriptions'
	end
  get "/users/edit_profile/:profile_id" => "users#edit_profile"
  get "/users/remote_profile/:profile_id" => "users#remote_profile"

 ##USERS PAGES ROUTES STARTS HERE####

 ##PLANS PAGES ROUTES STARTS HERE####
  get '/plans' => 'plans#all_plans'
  get '/plans/m_plans' => 'plans#mobile_all_plans'
 
  get '/plans/plans_summary' => 'plans#plans_summary'
  get '/plans/m_plans_summary' => 'plans#mobile_plans_summary'
 
  get '/plans/plans_purchase' => 'plans#plans_purchase'
  get '/plans/m_plans_purchase' => 'plans#mobile_plans_purchase'
 
  post '/plans/payment_url' => 'plans#payment_url'
  post '/plans/m_payment_url' => 'plans#mobile_payment_url'

  get '/plans/purchase_plans' => 'plans#purchase_plans'
  get '/plans/m_purchase_plans' => 'plans#mobile_purchase_plans'
 
  get '/payment/payment_processing' => 'plans#payment_processing'
  get '/payment/m_payment_processing' => 'plans#mobile_payment_processing'
 
  get '/payment/payment_success' => 'plans#payment_success'
  get '/payment/m_payment_success' => 'plans#mobile_payment_success'
 
  get '/payment/payment_failed' => 'plans#payment_failed'
  get '/payment/m_payment_failed' => 'plans#mobile_payment_failed'
 
  post '/payment/payment_canceled' => 'plans#payment_canceled'
  post '/payment/m_payment_canceled' => 'plans#mobile_payment_canceled'
 
  # post '/payment/payment_response' => 'plans#payment_response'
  # post '/payment/m_payment_response' => 'plans#mobile_payment_response'
 
  match 'payment/payment_response' => 'plans#payment_response', via: [:get, :post]
  match 'payment/m_payment_response' => 'plans##mobile_payment_response', via: [:get, :post]
 
  get '/plans/apply_promocode' => 'plans#apply_promocode'
  # get '/plans/m_apply_promocode' => 'plans##mobile_apply_promocode'

  get '/plans/view_plans' => 'plans#view_plans'
  get '/plans/m_view_plans' => 'plans##mobile_view_plans'

  get '/plans/plan_details/:id', to: 'plans#plan_details', as: 'plan'
  get '/plans/m_plan_details/:plan_id' => 'plans##mobile_plan_details'

   get '/plans/modify_plans' => 'plans#modify_plans'
  get '/plans/m_modify_plans' => 'plans##mobile_modify_plans'

 ##PLANS PAGES ROUTES ENDS HERE####


 ###SEARCH ROUTES STARTS HERE#################
 match "/search" => "search#index",via: [:get,:post]
 # get "/search" => "search#index"

 ###SEARCH ROUTES ENDS HERE#################


 ##CATALOGS PAGES ROUTES STARTS HERE####
 get "/all_channels" => "catalogs#all_channels"
 get "/:catalog_name" => "catalogs#show_catalog_item"
 get "/:catalog_name/all" => "catalogs#all_items_list"
 get "/:catalog_name/:show_name" => "catalogs#item_details"
 get "/:catalog_name/others/all" => "catalogs#other_tvshows"
 get "/:catalog_name/:show_name/all_episodes" => "catalogs#all_episodes"
 get "/:catalog_name/:genre/all" => "catalogs#genre_all_items"
 get "/:catalog_name/:show_name/:item_name" => "catalogs#episode_details"
 ##CATALOGS PAGES ROUTES ENDS HERE####

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  include PlansHelper

  def all_plans
    cookies[:user_id] = params["app_session_id"] if params["app_session_id"].present?
    user_session = cookies[:user_id].to_s
    user_plans = Ott.user_plans(user_session)
     if user_plans["data"].count >0
       redirect_to plans_view_plans_path
     else
    response = Ott.subscription_plans
    @all_plans = response["data"]["catalog_list_items"]
    @cat_titles = []
    @all_plans.each do |plan|
      if plan["plans"].present?
     plan["plans"].each do |pl|
        title = "#{plan['category']}-#{pl['title']}"
        @cat_titles <<  title.downcase
     end
     end
    end
    end
  end

  def plans_summary
    response = Ott.subscription_plans
    @all_plans = response["data"]["catalog_list_items"]
    @all_access_packs = @all_plans.last["catalog_list_items"].last

    user_session = cookies[:user_id].to_s
    @user_plans = Ott.user_plans(user_session)
    if @user_plans["data"].map{|s| s["subscription_id"]}.uniq.include?(params["plans"].split("|")[5])
      current_plan =    @user_plans["data"].map{|s| s if s["subscription_id"] == params["plans"].split("|")[5] }.compact
     # HTTP.get "catalogs/5b3c917fc1df417b9a00002c/items/#{current_plan["subscription_id"]}?auth_token=Ts4XpMvGsB2SW7NZsWc3&region=#{@region}" ,"catalog"
         new_cat_id = params["plans"].split("|")[5]
        new_plan_id =  params["plans"].split("|")[0]
        cur_cat_id = current_plan[0]["subscription_id"]  
        cur_plan_id = current_plan[0]["plan_id"]  
         modify_params =  {"auth_token": "Ts4XpMvGsB2SW7NZsWc3","data": {"add_plans":  { "plan_id": new_plan_id,"subscription_category_id": new_cat_id},    "modify_plans":{"current_plan_id": cur_plan_id,"subscription_category_id": cur_cat_id},"region": @region}}
       @response =  HTTP.post_https "users/#{cookies[:user_id]}/get_modified_amount", modify_params
     
       #{"total_amount"=>51.56, "currency"=>"INR", "subscription_category_id"=>"5b67ec33c1df415e28000030", "plan_id"=>"5b67ec33c1df415e2800002f", "category"=>"kids", "remaining days"=>31}
       render "modify_plans_summary"
    end

    if params["plans"].present? && params["plans"].split(",").count == 2
      plan_title = params["plans"].split(",").map{|a| a.split("|")[2] }.last
      items  =   Ott.get_catalog_details("5b3c917fc1df417b9a00002c")
      @combo_plan = items["data"]["items"].last
      @combo_pack = items["data"]["items"].last["plans"].map{|e| e if e["title"].downcase == plan_title.downcase}.compact.last
      render "combo_plans_summary"
    end
  end

  def payment_url
    if @region == "US"
      payment_gateway = "adyen"
    else
      payment_gateway = "ccavenue"
    end
    platform = "android"  #TODO
    if params["combo_pack_id"].blank?
      plans = params["plans"].split(",")
    else
      plans = []
    end
    if plans.count != 2 &&  !plans.empty?
      packs = []
      plan =  plans[0]
      content_id  = plan.split("|")[5]
      pack_id  = plan.split("|").first
      pd  =   HTTP.get "catalogs/5b3c917fc1df417b9a00002c/items/#{content_id}?auth_token=Ts4XpMvGsB2SW7NZsWc3&region=#{@region}" ,"catalog"
      sp = pd["data"]["plans"].map{|e| e if e["id"] == pack_id}.compact.last

      all_price = sp["price"]
      currency = sp["currency"]
      price_charged = sp["discounted_price"]
      if params["modified_amount"].present? 
        all_price_charged = params["modified_amount"]
      else
        all_price_charged = params["disc_amount"] == "null" ? price_charged : params["disc_amount"]
      end
      sub_pack = {}
      sub_pack["plan_categories"] = [pd["data"]["category"]]
      sub_pack["category_type"] = pd["data"]["category_type"]
      sub_pack["category_pack_id"] = content_id
      sub_pack["subscription_catalog_id"] = pd["data"]["catalog_id"]
      sub_pack["plan_id"] = sp["id"]
      packs << sub_pack
    else
      pack_id =params["combo_pack_id"]
      items  =   Ott.get_catalog_details("5b3c917fc1df417b9a00002c")
      @combo_plan = items["data"]["items"].last
      @combo_pack = items["data"]["items"].last["plans"].map{|e| e if e["id"] == pack_id}.compact.last
      all_price = @combo_pack["price"]
      all_price_charged = params["disc_amount"] == "null" ? @combo_pack["discounted_price"] : params["disc_amount"]
      currency = @combo_pack["currency"]
      packs = []
      sub_pack = {}
      sub_pack["plan_categories"] = params["plans"].split(",").map{|a| a.split("|")[6] }
      sub_pack["category_type"] = @combo_plan["category_type"]
      sub_pack["category_pack_id"] = @combo_plan["category_id"]
      sub_pack["subscription_catalog_id"] = @combo_plan["catalog_id"]
      sub_pack["plan_id"] = @combo_pack["id"]
      packs << sub_pack
    end
    if  params["coupon_code"] == "null"
      payment_info = {"net_amount": all_price, "price_charged": all_price_charged,"currency": currency, "packs": packs }
    else
      coupon_code = params["coupon_code"]
      coupon_code_id = params["coupon_code_id"]
      payment_info = {"net_amount": all_price, "price_charged": all_price_charged,"currency": currency, "packs": packs, "coupon_code": coupon_code,"coupon_code_id": coupon_code_id  }
    end
    transaction_info = 	{"app_txn_id":"", "txn_message":"One Day Pack_10.00", "txn_status":"init", "order_id":"", "pg_transaction_id":""	}
    user_info = {"email": cookies[:user_login_id], "mobile_number": cookies[:user_login_id]}

    browser = Browser.new(:ua => request.env["HTTP_USER_AGENT"], :accept_language => "en-us")
    device_os = "NA" #,browser.ios? ? 'iOS' : (browser.android? ? 'android' : browser.platform.to_s)
    browser_name = browser.name.split(" ").join("_")
    browser_version=  "NA" #browser.full_version
    device_type = "NA" #browser.mobile? ? 'mobile' : browser.tablet? ? 'tablet' : 'desktop'
    subscription_status =  cookies["is_subscribed"] == "yes" ? "subscribed" : "unsubscribed"
    platform  = cookies["browser_type"] == "mobile" ? "WAP" : "WEB"
    device_brand = 'NA'
    device_model = 'NA'
    device_imei = 'NA'
    operator = cookies['operator'] != "undefined"  ? cookies['operator'] : 'NA'
    internet_network = 'NA'
    isp_name = 'NA'

    miscellaneous ={"browser": browser_name, "device_brand": device_brand,"device_IMEI": device_imei, "device_model": device_model, "device_OS": device_os ,"device_type": device_type ,"inet": internet_network,"isp": isp_name,"operator": operator}

    us = get_signature_key(payment_info[:packs])


if params["modified_amount"].present? 
    user_session = cookies[:user_id].to_s
    @user_plans = Ott.user_plans(user_session)
 #if @user_plans["data"].map{|s| s["subscription_id"]}.uniq.include?(params["plans"].split("|")[5])
  current_plan =    @user_plans["data"].map{|s| s if s["subscription_id"] == params["plans"].split("|")[5] }.compact
 # HTTP.get "catalogs/5b3c917fc1df417b9a00002c/items/#{current_plan["subscription_id"]}?auth_token=Ts4XpMvGsB2SW7NZsWc3&region=#{@region}" ,"catalog"
    #  new_cat_id = params["plans"].split("|")[5]
    # new_plan_id =  params["plans"].split("|")[0]
    cur_cat_id = current_plan[0]["subscription_id"]  
    cur_plan_id = current_plan[0]["plan_id"]  
    modify_user_plans = {"current_plan_id": cur_plan_id,"current_subscription_category_id": cur_cat_id}

    purchase_params = {
        "auth_token":"Ts4XpMvGsB2SW7NZsWc3", "us": us, "region": @region, "payment_gateway": payment_gateway,"platform": platform,
    "payment_info": payment_info,
    "transaction_info": transaction_info,
    "modify_user_plans": modify_user_plans,
    "user_info": user_info,
    "miscellaneous": miscellaneous
    }
  else
    purchase_params = {
    "auth_token":"Ts4XpMvGsB2SW7NZsWc3", "us": us, "region": @region, "payment_gateway": payment_gateway,"platform": platform,
    "payment_info": payment_info,
    "transaction_info": transaction_info,
    "user_info": user_info,
    "miscellaneous": miscellaneous
    }
  end
# byebug
# raise purchase_params.inspect
    response =  HTTP.post_https "users/#{cookies[:user_id]}/transactions", purchase_params
    if payment_gateway == "adyen"
      render json: {:message => "adyen payment iniated",:init_data => response["data"] } , status: :ok
    else
# byebug
# raise payment_info.inspect
      payment_url = "#{response['data']['payment_url']}&encRequest=#{response['data']['msg']}&access_code=#{response['data']['access_code']}"
      render json: {:message => "ccavenue payment iniated",:payment_url => payment_url} , status: :ok
    end
  end


  def purchase_plans
    payment_gateway = "admin"
    platform = "android"

    if params["combo_plan_id"].blank?
      plan_id = params["plans"].split(",").map{|a| a.split("|")[-2]}[0]
      pack_id = params["plans"].split(",").map{|a| a.split("|")[0]}[0]
    else
      plan_id = params["combo_plan_id"]
      pack_id = params["combo_pack_id"]
    end
    pd  =   HTTP.get "catalogs/5b3c917fc1df417b9a00002c/items/#{plan_id}?auth_token=Ts4XpMvGsB2SW7NZsWc3&region=#{@region}" ,"catalog"
    sp = pd["data"]["plans"].map{|e| e if e["id"] == pack_id}.compact.last
    if @region == "IN"
      price_charged = sp["pg_price"]["cc_avenue"]
    else
      price_charged =  sp["pg_price"]["adyen"]
    end

    if params["combo_plan_id"].blank?
      plan_categories = [ pd["data"]["category"]]
    else
      plan_categories = params["plans"].split(",").map{|a| a.split("|")[6] }
    end


    payment_info = { "price_charged": price_charged,"currency": sp["currency"],
    "packs":[
        {"plan_categories": plan_categories,
    "category_type": pd["data"]["category_type"],
    "subscription_catalog_id": pd["data"]["catalog_id"],
    "category_pack_id": plan_id,
    "plan_id": sp["id"]
    }]}
    adyen_encrypted_data = params["adyen-encrypted-data"]
    user_info = {"email": cookies[:user_login_id], "mobile_number": cookies[:user_login_id]}
if params["modified_amount"].present? 
    user_session = cookies[:user_id].to_s
    @user_plans = Ott.user_plans(user_session)

app/helpers/plans_helper.rb
module PlansHelper
	def get_gradient title
		case title
    when "Bollywood classic packs"
      return "gradient2"
		when "Bollywood packs"
			return "gradient3"
     when "Kids pack"
      return "gradient5"
    when "Punjabi packs"
      return "gradient8"
    when "Gujarathi packs"
      return "gradient4"
    when "Bhakti packs"
      return "gradient6"
    when "Ibadaat packs"
      return "gradient7"
    when "Combo packs"
      return "gradient4"
    end
	end

  def get_gradient_color title
    case title
    when "Bollywood classic packs"
      return "gradientbg2"
    when "Bollywood packs"
      return "gradientbg3"
     when "Kids pack"
      return "gradientbg5"
    when "Punjabi packs"
      return "gradientbg8"
    when "Gujarathi packs"
      return "gradientbg4"
    when "Bhakti packs"
      return "gradientbg6"
    when "Ibadaat packs"
      return "gradientbg7"
    when "Combo packs"
      return "gradientbg4"
    when "All access pack"
      return "gradientbg1"
    end
  end

  def get_signature_key(packs)
   secret_key = "7c32c524a67f405812ca"
    all_plan_id = "" 
    packs.each do |p| 
    plan_id = p["plan_id"].blank? ? p[:plan_id] : p["plan_id"]
    all_plan_id += plan_id 
    end 
    session_id = cookies[:user_id]
    region = @region
    sec_key = secret_key+session_id+region+all_plan_id 
    md5_sign = Gibberish::MD5(sec_key) 
    return md5_sign
  end
end

app/views/plans/current_plans.html.erb
<section class="onboarding-bg min-height-div padding-top-85 padding-top-145  padding-left-15 padding-right-15">
  <div class="onboarding-payment-contianer margin-bottom-30">
  	<div class="row">
  		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-">
  			<h2 class="pull-left w-100 margin-top-25">Plan Details</h2>  			
  		</div>
  	</div>
		<div class="row">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- current_plans plans_details_page">
				<div class="pull-left w-100 margin-bottom-25">
            <div class="card">
              <div class="card-body">
                <h5 class="gradient1 pull-left">Bollywood Classic<br><span class="text-uppercase active_plan font-semibold">active plan</span></h5>
								<span class="pull-right text-uppercase text-right">
									<small>monthly</small> 
									<br><b>49</b>
								</span> 
								<div class="pull-left w-100">
									<p class="pull-left margin-top-10 margin-bottom-0 margin-right-25">
										<span class="text-uppercase"><small>transaction id</small></span><br>
										<span class="date">1234567890</span>
									</p>
									<p class="pull-left margin-top-10 margin-bottom-0 margin-right-25">
										<span class="text-uppercase"><small>plan duration</small></span><br>
										<span class="date">21 Jul 2018 - 20 Aug 2018</span>
									</p>       
								</div>	
								<div class="pull-left w-100">
								<div class="pull-left margin-top-10 margin-bottom-0">
									<p class="margin-bottom-0"><span class="text-uppercase"><small>payment method</small></span><br></p>
									<p class="margin-bottom-0 current_plan_payment_method">
										<img src="/assets/master-card.png" alt="" title="">
										<span class="label_pwd">.... .... ....</span><span>9012</span>
									</p>	
								
              </div>
              <div class="pull-right margin-top-10">
              	<small><a href="javascript:;" class="text-uppercase font-medium">edit</a></small>
              </div>
            </div>
          </div>
			</div>
		</div>
	</div>
	<%=render "layouts/page_height_setting"%>
</section>

app/views/plans/mobile_payment_canceled.html.erb
<section class="min-height-div transation_status_page padding-top-85 padding-top-145">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- no-content-wrap no_content_plans text-center">
      <h2 class="block margin-bottom-10">Transaction Cancelled</h2>
      <img src="/assets/transaction_failed.svg" class="status_image" alt="" title="">
      <!-- <p class="font-light margin-bottom-15">Your payment of Rs. 45 could not be processed</p>  -->
      <p class="font-light margin-bottom-15">Reason: <%=@resp["error"]["message"]%>&nbsp;&nbsp;(Error: <%=@resp["error"]["code"]%>)</p>
      <!-- <p class="font-light margin-bottom-0">Transation ID</p>  -->
      <!-- <p class="margin-bottom-0 font-medium margin-bottom-15"><strong>999999</strong></p> -->
      <a href="/plans" class="radius-button margin-bottom-25" id="">Try again</a>
    </div>
  </div>
  <%=render "layouts/page_height_setting"%>
</section>

app/views/plans/mobile_payment_response.html.erb
<%="payment_success"%>
<section class="min-height-div transation_status_page padding-top-85 padding-top-145">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- no-content-wrap no_content_plans text-center">
      <h2 class="block margin-bottom-10">Transaction Status</h2>
      <img src="/assets/transaction_successful.svg" class="status_image" alt="something went wrong" title="something went wrong">
      <p class="font-light margin-bottom-15"><%=@resp%></p>
      <!--    <p class="font-light margin-bottom-0">Transation ID</p>
         <p class="margin-bottom-0 font-medium margin-bottom-15"><strong>999999</strong></p> -->
      <a href="/" class="radius-button text-uppercase margin-bottom-25" id="">continue browsing</a>
    </div>
  </div>
  <%=render "layouts/page_height_setting"%>
</section>

app/views/plans/mobile_payment_success.html.erb
<%="payment_success"%>
<section class="min-height-div transation_status_page padding-top-85 padding-top-145">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- no-content-wrap no_content_plans text-center">
      <h2 class="block margin-bottom-10">Transaction Successful</h2>
      <img src="/assets/transaction_successful.svg" class="status_image" alt="something went wrong" title="something went wrong">
      <p class="font-light margin-bottom-15"><%=@resp["data"]["message"]%></p> 
   <!--    <p class="font-light margin-bottom-0">Transation ID</p> 
      <p class="margin-bottom-0 font-medium margin-bottom-15"><strong>999999</strong></p> -->
      <a href="/" class="radius-button text-uppercase margin-bottom-25" id="">continue browsing</a>
    </div>
  </div>
  <%=render "layouts/page_height_setting"%>
</section>

app/views/plans/mobile_plan_details.html.erb
<%="current_plans"%>
<%="current_plans"%>
<%="current_plans"%>
<%="current_plans"%>
<%="current_plans"%>

app/views/plans/mobile_transaction_failed.html.erb
<section class="min-height-div transation_status_page margin-top-30">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- no-content-wrap no_content_plans text-center margin-top-25">
      <h2 class="block margin-bottom-10"><!-- <img src="/assets/back_arrow.svg" class="back_arrow" alt="back arrow" title="back arrow"> --> Transaction Failed</h2>
      <img src="/assets/transaction_failed.svg" class="status_image" alt="something went wrong" title="something went wrong">
      <p class="font-light margin-bottom-15">Your payment of Rs. 45 could not be processed</p> 
      <p class="font-light margin-bottom-15">Reason: The system is currently unavailable (Error 1234)</p> 
      <p class="font-light margin-bottom-0">Transation ID</p> 
      <p class="margin-bottom-0 font-medium margin-bottom-15"><strong>999999</strong></p>
      <a href="/" class="radius-button" id="">Try again</a>
    </div>
  </div>
</section>

app/views/plans/mobile_view_plans.html.erb
<%= "MY PLANS"%>

app/views/plans/payment_failed.html.erb
<section class="min-height-div transation_status_page padding-top-85 padding-top-145">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- no-content-wrap no_content_plans text-center">
      <h2 class="block margin-bottom-10">Transaction Failed</h2>
      <img src="/assets/transaction_failed.svg" class="status_image" alt="" title="">
      <!-- <p class="font-light margin-bottom-15">Your payment of Rs. 45 could not be processed</p>  -->
      <p class="font-light margin-bottom-15">Reason: <%=@resp["error"]["message"]["message"]%>&nbsp;&nbsp;(Error: <%=@resp["error"]["code"]%>)</p>
      <!-- <p class="font-light margin-bottom-0">Transation ID</p>  -->
      <!-- <p class="margin-bottom-0 font-medium margin-bottom-15"><strong>999999</strong></p> -->
      <a href="javascript:;" class="radius-button margin-bottom-25" id="" onclick="tellAndroidFailed('<%=@resp["error"]["message"]["message"]%>')">Try again</a>
    </div>
  </div>
  <%=render "layouts/page_height_setting"%>
</section>
<script type="text/javascript">
    function tellAndroidFailed(message) {
      console.log(message);
      Android.failed(message);
      window.location.href = "/plans"
    }
</script>

app/views/plans/view_plans.html.erb
<section class="onboarding-bg min-height-div padding-top-85 padding-top-145  padding-left-15 padding-right-15">
  <div class="onboarding-payment-contianer margin-bottom-30">
  	<div class="row">
  		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-">
  			<h2 class="pull-left margin-top-25">Current Plans</h2>
  			<a href="/plans/modify_plans" class="text-uppercase font-medium pull-right margin-top-25 padding-top-5">Modify</a>
  		</div>
  	</div>
		<div class="row">
			<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- current_plans">
			<%@current_plans.each do |plan|%>
			<%= link_to plan_path(plan["id"]) do %>
				<div class="pull-left w-100 margin-bottom-25">
            <div class="card">
              <div class="card-body">
               <h5 class="gradient1 pull-left" style="<%=get_title_item_color(plan["plan_categories"].first) if plan["plan_categories"].present?%>" id="heading_title_color"><%=plan["title"]%><%=plan["subscription_title"]%></h5>
								<span class="pull-right text-uppercase">
									<small><%=plan["plan_title"]%></small> 
									<br><b><%=plan["currency"]%>&nbsp;<%=plan["price_charged"]%></b>
								</span>          
								<p class="pull-left w-100 text-uppercase margin-top-20 margin-bottom-0">
									<span><small>next billing</small></span><br>
									<span class="date"><%=Time.parse(plan["billing_date"]).strftime("%d %b %Y") if plan["billing_date"].present?%></span>
								</p>      
              </div>
            </div>
          </div>
          <%end%>
          <%end%>
			</div>
		</div>

<%if @expired_plans.present?%>
		<div class="row">
  		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col- prev_plans">
  			<h2 class="block">Previous Plans</h2>
			<%@expired_plans.each do |plan|%>
  		<div class="pull-left w-100 margin-bottom-25">
          <div class="card">
            <div class="card-body">
              <h5 class="gradient1 pull-left"><%=plan["subscription_title"]%></h5>
							<span class="pull-right text-uppercase">
								<small><%=plan["plan_title"]%></small> 
								<br><b><%=plan["currency"]%>&nbsp;<%=plan["price_charged"]%></b>
							</span>          
							<p class="pull-left w-100 text-uppercase margin-top-20 margin-bottom-0">
								<span><small>exprired on</small></span><br>
								<span class="date"><%=Time.parse(plan["valid_till"]).strftime("%d %b %Y") if plan["valid_till"].present?%></span>
							</p>      
            </div>
          </div>
        </div>
<%end%>
  		</div>
  	</div>
<%end%>
  </div>
  <%=render "layouts/page_height_setting"%>
</section>